### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'dit\\2010\\Jan\\18\\"save_sent_mail"  on'

### ISSUE THREAD

**Issue by KeesCopyright** [mjseeley/Gmail-Attachment-Downloader#9]
Sorry I am an ultra NOOB. But im running into this. Chatgpt suggests sanitising the function but as of this moment i dont know how to do that. I will however attempt to implement this improvement and will post a pull/push request when i figure it out.

**Comment by mjseeley** [comment]
If you can get me the line number where issue occurred or more of the actual error message. I can take a look.

**Comment by KeesCopyright** [comment]
I tried to add the updated py file here but not allowed. I tried creating a pull request but something something something branches? So ill just answer the question here. I added import re 
after line "from enum import Enum"
added
import re
And this line 
 file_name = re.sub(r'[\\/*?:"<>|]', '_', file_name)
instead of your
         file_name = file_name.replace("/", "_")
after the mime thing

**Comment by KeesCopyright** [comment]
sorry for my ultra NOOBness, and super thankyou for this script. its def doing its job.
Had indead to jump through hoops with the 2fa and apppassword but it works

**Comment by mjseeley** [comment]
ChatGPT is not wrong. I should be sanitizing the files paths better based on OS type, Windows is way more picky about special Characters in files paths and names than Linux is.

**Comment by mjseeley** [comment]
Added some changes to file path construction now using os.path.join() to keep things cross platform. I also added some file name sanitization too. I hope this fixes your issue.
